from abc import ABC, abstractmethod
from typing import List
import httpx
from openai import AsyncOpenAI
from app.core.config import settings

class BaseEmbedding(ABC):
    """Abstract base class defining interface for generating text embeddings."""
    
    @abstractmethod
    async def embed_query(self, text: str) -> List[float]:
        """Generate embedding vector for a query string."""
        pass

    @abstractmethod
    async def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """Generate list of embedding vectors for a list of document strings."""
        pass

    @property
    @abstractmethod
    def dimension(self) -> int:
        """The size/dimension of the vector generated by this embedding model."""
        pass


class OpenAIEmbedding(BaseEmbedding):
    """
    Generates text embeddings using OpenAI API.
    - Default Model: 'text-embedding-3-small' (1536 dimensions)
    - If you want text-embedding-3-large (3072 dimensions), change model and dimension variables.
    """
    def __init__(self, model: str = "text-embedding-3-small"):
        self.model = model
        self.client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)
        self._dimension = 1536 if "ada-002" in model or "3-small" in model else 3072

    async def embed_query(self, text: str) -> List[float]:
        """Generate a 1D vector representation for a single search query."""
        response = await self.client.embeddings.create(
            input=[text],
            model=self.model
        )
        return response.data[0].embedding

    async def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """Generate a list of 1D vector representations for a batch of documents/chunks."""
        if not texts:
            return []
        response = await self.client.embeddings.create(
            input=texts,
            model=self.model
        )
        return [item.embedding for item in response.data]

    @property
    def dimension(self) -> int:
        return self._dimension


class SentenceTransformerEmbedding(BaseEmbedding):
    """
    Generates embeddings locally using SentenceTransformers (cpu/gpu).
    - Default Model: 'all-MiniLM-L6-v2' (384 dimensions - extremely fast, lightweight, and local).
    - If you want to use a larger local model like 'all-mpnet-base-v2' (768 dimensions), update model_name below.
    """
    def __init__(self, model_name: str = "all-MiniLM-L6-v2"):
        self.model_name = model_name
        self._model = None  # Loaded lazily to avoid slowdown during startup
        self._dimension = 384  # Change to match dimension if you update the model name

    def _load_model(self):
        """Loads the local sentence-transformer model lazily on first query call."""
        if self._model is None:
            from sentence_transformers import SentenceTransformer
            # Downloads/loads model files into local cache directory (.cache/torch/sentence_transformers)
            self._model = SentenceTransformer(self.model_name)
        return self._model

    async def embed_query(self, text: str) -> List[float]:
        """Runs embedding generation locally, executing in a separate thread loop to keep FastAPI async loop non-blocking."""
        model = self._load_model()
        import asyncio
        loop = asyncio.get_event_loop()
        embeddings = await loop.run_in_executor(
            None, 
            lambda: model.encode([text], convert_to_numpy=True)
        )
        return embeddings[0].tolist()

    async def embed_documents(self, texts: List[str]) -> List[List[float]]:
        """Runs batch embedding generation locally, executing in a separate thread loop."""
        if not texts:
            return []
        model = self._load_model()
        import asyncio
        loop = asyncio.get_event_loop()
        embeddings = await loop.run_in_executor(
            None, 
            lambda: model.encode(texts, convert_to_numpy=True)
        )
        return [emb.tolist() for emb in embeddings]

    @property
    def dimension(self) -> int:
        return self._dimension


class EmbeddingFactory:
    """
    Factory to resolve embedding model generators.
    - Used during ingestion (parsing documents) and search retrieval.
    """
    @staticmethod
    def get_embedding_provider(provider_name: str) -> BaseEmbedding:
        provider = provider_name.lower()
        if provider == "openai":
            return OpenAIEmbedding()
        elif provider == "local" or provider == "sentencetransformer":
            return SentenceTransformerEmbedding()
        else:
            raise ValueError(f"Unsupported embedding provider: {provider_name}")
